config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy]

  root "top#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :img, presence: true
  validates :content, presence: true

  mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_picture, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(pictures_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(pictures_params)
    #@picture.user_id = current_user.id
    if @picture.save
     redirect_to pictures_path, notice:"写真を投稿しました！"
     #NoticeMailer.sendmail_blog(@blog).deliver
    else
     render 'new'
    end
  end

  def edit
  end

  def update
    if @picture.update(pictures_params)
      redirect_to pictures_path, notice:"写真を編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path, notice: "ブログを削除しました！"
  end

  private
    def pictures_params
      params.require(:picture).permit(:img,:content,:img_cache)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
<header>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Instagram", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "写真一覧", pictures_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

<footer>
  <p>運営会社DIVE INTO CODE株式会社</p>
  <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
</footer>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>

  <%= f.label :写真 %>
  <%= f.file_field :img, class: 'form-control' %>
  <%= f.hidden_field :img_cache %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block'%>
<% end %>

<%= link_to "写真一覧画面にもどる", pictures_path %>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-offset-2 col-sm-10 col-lg-8">
    <p><%= notice %></p>
    <h1>写真一覧</h1>
    <%= link_to "写真を投稿する", new_picture_path, class: 'btn btn-default' %>
    <% @pictures.each do |picture| %>
    <div class="row">
      <div class="clear field-blogs-content ">
        <div><%= image_tag(picture.img, :class => "img") %></div>
        <p><%= picture.content %></p>
        <%= link_to "編集", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
        <%= link_to "削除", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
      </div>
    </div>
    <% end %>
  </div>
  <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id ="move-page-top">▲</a></p>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<section class="main-header">
  <p class="flash"><%= notice%><%= alert%></p>
</section>